permalink: pretty
collections:
  notes:
    output: true
  art:
    output: true
  thinking:
    output: true

defaults:
  - scope:
      type: posts
      category: music
    values:
      permalink: :categories/:title
      layout: music
  - scope:
      type: posts
      category: thinking
    values:
      layout: focus

exclude:
    - art-originals
    - notes-originals