permalink: pretty
collections:
  notes:
    output: true
  art:
    output: true
  thinking:
    output: true
  doing:
    output: true

defaults:
  - scope:
      type: posts
      category: music
    values:
      permalink: :categories/:title
      layout: music